### ISSUE TITLE
Port build to newer tools

### ISSUE THREAD

**Issue by Lewiscowles1986** [roelandjansen/pcmos386v501#13]
It would be incredibly useful if this could build under newer tools. Not asking the authors or maintainers to handle (or anyone else). I would just like the issue to stand until it's managed by someone. It'd be a very nice enhancement.

**Comment by roelandjansen** [comment]
could you define "newer tools" ?

Like newer versions of the old borland c compiler etc? (Note that the latter seems to be open/free)

**Comment by andrewbird** [comment]
@roelandjansen I've stumbled across this from [dosemu2](https://github.com/stsp/dosemu2) and only just started playing with pcmos at the moment. One issue we have is that FreeDOS can't be included in Debian (and so we can't depend upon it) because of its build requirements of non-free tools conflicting with the Debian ethos. I'm not sure if it's possible for pcmos, but if you do change tools it would be wise to select those that may allow you to get into Debian.
Hope it helps :smile:

**Comment by Lewiscowles1986** [comment]
I meant modern compiler and linkers, not Borland. Sorry for any confusion.

**Comment by dcoshea** [comment]
@andrewbird Is there a bug anywhere describing precisely what the issues with FreeDOS are with regards to Debian's requirements?  I seem to recall some things _could_ be built with Borland's Turbo C, but I don't know if that was a requirement.  I also understand that Open Watcom's license agreement isn't considered free enough, see e.g. [this post and its replies](http://www.spinics.net/lists/linux-8086/msg00831.html); I assume the same concerns would be held by Debian.

There are certainly some compilers which I think meet Debian's requirements that can generate DOS .COM files, including the recently-released/revamped gcc-ia16, but I don't think there are any that can generate .EXE files, and PC-MOS includes some of those.  https://lwn.net/Articles/735734/ suggests that gcc-ia16 support for generating .EXEs may be in progress right now.

**Comment by roelandjansen** [comment]
regarding the old borland c compiler -- I have tracked it back to the company that currently holds the copyright. This is the same company that has brief as editor.

Having said that all...


when it comes to building an eventual other toolchain -- that is super-cool but when it comes to maintainability et al, I would suggest to be a bit defensive. I know that debian is used by many people for some reasons I still don't understand for 20+ years.  So let's see what works and if there are packages available, let's find out if other platforms (enterprise-wise) are also supported.

Best would be if a single compiler codebase could/would be built for the main packages (deb, rpm). FOr instance the OBS is a good place where this can be automatically built.

Now. when it comes to integration -- I am toying with the idea to have jenkins added so that builds are tested after a merge/push and the artefacts are then sent back to the releases page here.

**Comment by andrewbird** [comment]
Openwatcom in Debian wouid be the ideal solution for FreeDOS inclusion in Debian, but unless its licence gets changed it's not likely to happen, see [rfp](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=376431)
There's a new github for openwatcom that does see development, there's still an ongoing [thread](https://github.com/open-watcom/open-watcom-v2/issues/271) about licensing change. It seems that SAP (new owner of SyBase) has no interest in it any more; perhaps some high profile figure could prod them into sorting out the licence (needs an NVidia moment :smile:)
Thanks for the link about gcc-ia16, I didn't know about that. It seems like there's a [PR](https://github.com/crtc-demos/gcc-ia16/pull/2) for far pointer support, which is always the missing piece. Of course having a compatible libc is also required.
I do use [djgpp](http://www.delorie.com/djgpp) (as cross compiler) to create simple test executables for dosemu2, but of course there are no far pointers as it's 32bit, and again it's not in Debian.

**Comment by dcoshea** [comment]
> regarding the old borland c compiler -- I have tracked it back to the company that currently holds the copyright.

They have released some of their older compilers for free, perhaps they will release this one.  I hope you can convince them @roelandjansen :)  Would they ever release the source code for it, and do so under a "truly free" license agreement, though?

> I would suggest to be a bit defensive.

As one might guess from issue #12, I personally don't know whether I have built everything that can be built or needs to be built, or whether any of the artefacts I built actually work.

> I am toying with the idea to have jenkins added

CI is an interesting problem when some of the build tools are non-free and hence can't easily be fetched at build time as could otherwise be done with Travis CI.  I suppose that using a completely free toolchain would help in that regard!

Thanks @andrewbird for the RFP reference!

**Comment by stsp** [comment]
I would invite people discussing freedos
to our bugtracker, but not this one. :)
As for pcmos, it seems to be you don't
need a C compiler at all to build its kernel.
There are some utils code that require
a C compiler, but the kernel seems to be
all in asm. So it may be quite simple to
get something bootable.

**Comment by roelandjansen** [comment]
the kernel indeed is all asm. some of the tooling is asm as well and others are in C.
So yes, with some fiddling you could build it with asm -- and as long as the assembler
understands the syntax, any assembler would do.

As stated, thereare references for history purposes too and if we finally have something that works, we coulld start using that.

**Comment by pgiffuni** [comment]
Porting it to OpenWatcom would certainly be an important advance. It is important to be able to autohost  both the OS and the compiler, plus OW used to be the top of the line compiler for DOS/win32/os2 and some 32bit DOS variant that I forget about.

**Comment by galazwoj** [comment]
For  assembly  code  there  is  nothing  but  to  use  masm  5.1, for  C code  I  use  Microsoft  C5.1  but  plan  to  switch  to  Microsoft  C  7.0 and  later  to  Openwatcom  2.0c.  I   am  at  the  moment  when  stuff  compiles and  amd  trying  to  recreate  all  programs  supplied  with  pcmos. Sorry ,  no  borland  compiler  😣

**Comment by tkchia** [comment]
Hello @andrewbird ,

> It seems like there's a PR for far pointer support, which is always the missing piece. Of course having a compatible libc is also required.

Thanks for the shout-out. :)  Regarding the C library, the IA-16 port of `newlib` currently used by `gcc-ia16` does include the ANSI C stuff and (I think) much of the POSIX-ish stuff such as `<stdio.h>`, `<stdint.h>`, `<unistd.h>`, etc., so these should not be too much of a problem.

However, `newlib-ia16` does not have the extra IBM PC-specific bells and whistles common to classical DOS compilers --- things like `<conio.h>`, `<dos.h>`'s `int86(`...`)`, and so on.

I had to deal with this issue when trying to (unofficially) port PDCurses to `gcc-ia16`, and I see that (at least) `ed.c` in the PC-MOS/386 code also uses some of these functions.

**Comment by stsp** [comment]
> For assembly code there is nothing but to use masm 5.1, for C
> code I use Microsoft C5.1 but plan to switch to Microsoft C 7.0 and later to Openwatcom 2.0c.

You don't seem to have mentioned what
are you planning to do with masm. I tried
jwasm just briefly but it doesn't seem to
compile MOS code right away.

**Comment by andrewbird** [comment]
Isn't there an 'ideal' mode that switches on mask support on was and presumably jwasm?

**Comment by stsp** [comment]
> switches on mask support on was and presumably jwasm?

Parse error. :)

**Comment by galazwoj** [comment]
1.  jwasm does not like variable names like 'tcb%rs0a', that is those including a percent sign
2. actually masm 5.1 is the standard for 16 bit assembly so it's hard to find something else right away, jwasm seems the only viable candidate though
3 there are aztec c and turbo pascal code that I think should be recoded to modern C first
4 source code for rsa.lib is missing and the library needs to be recovered

So masm 5.1 replacement can wait

**Comment by andrewbird** [comment]
Parse error! Sorry not at home for the next few days, so using a tablet with auto complete which mangles things it doesn't recognise!

**Comment by andrewbird** [comment]
https://github.com/tkchia/gcc-ia16/tree/gcc-6_3_0-ia16-tkchia is also something to look at

**Comment by the-grue** [comment]
Thanks for the tip!  I will take a look at this one as well.  Do you know if this will build and run on a DOS variant?  Does it have a matching binutils so you get an assembler, librarian(archiver), and linker?

**Comment by andrewbird** [comment]
I only know of the Linux build I'm afraid. You can get prebuilt binutils lib and compiler packages for ubuntu here https://launchpad.net/~tkchia/+archive/ubuntu/build-ia16 . it's at least good enough to build a working freedos kernel.

**Comment by tkchia** [comment]
Hello @the-grue , hello @andrewbird ,

Thanks for your interest!  As it happens, I am in the process of porting the IA-16 GCC toolchain --- that includes Binutils (`as`, `ld`, `ar`, etc.) and Newlib --- to a DJGPP/MS-DOS host, with the help of [Andrew Wu's cross-compiler](https://github.com/andrewwutw/build-djgpp).  The resulting toolchain will need a 32-bit machine, but it will produce 16-bit binaries.

I have got the toolchain semi-working (in a `dosemu` session; [source scripts available](https://github.com/tkchia/build-ia16/commit/179b2016d239cf91341db5da04b11a6bdd152ce4)).  However, it is still rather large, so I hope to reduce its space usage and also iron out a few kinks before actually releasing binaries for it.  Also, the tools do not include C++ support yet.

Thank you!

**Comment by the-grue** [comment]
Hi @tkchia!  Looking forward to it!

**Comment by tkchia** [comment]
Hello @the-grue, hello @andrewbird ,

I have [uploaded](https://github.com/tkchia/build-ia16/releases/tag/20180512-redist-djgpp) binaries for a DJGPP/MS-DOS host port of IA-16 GCC.  The binaries are still quite big, though.

I think it will be interesting to see if the toolchain can be used to help build the PC-MOS code.

Thank you!

**Comment by yuhong** [comment]
Digital Mars is now fully open source under Boost.

**Comment by src153** [comment]
Now is not the time to change toolchains. Closing.
