### ISSUE TITLE
MAKEMOS.BAT puts c:\borlandc on the PATH instead of c:\borlandc\bin

### ISSUE THREAD

**Issue by dcoshea** [roelandjansen/pcmos386v501#3]
`SOURCES/src/MAKEMOS.BAT` includes (as at 2d19bc15ddb2e9b3db832384377ea372a52608ef):

    path=c:\dos5.0;c:\borlandc;c:\lib;c:\bin

Borland C++ 3.1 doesn't have any useful binaries directly under the `c:\borlandc` directory.  The compiler binaries, etc. are in `c:\borlandc\bin`.  Adding `c:\borlandc` to the PATH adds only the executable `README.COM` to the PATH, which is probably not what was intended.

I'm not aware of this causing any problems with the build though.  I don't think that, given the current things built by MAKEMOS.BAT, it requires anything from Borland C++, although the build is failing before completion for me, so perhaps it's just not getting to that point.  Un-commenting these lines appears to be one way to add a dependency on Borland C++:

    rem CD\import
    rem make -f import.mak import.exe
    rem cd\export
    rem make -f export.mak export.exe

**Comment by roelandjansen** [comment]
I am in the process to see if I can get the original compiler officially "free" -- if hat is the case, I'll integrate it in the whole repo.

I recall from the 90's that I also had to adjust parts of my build structure.

**Comment by dcoshea** [comment]
That would be great, it's about time Borland/Embarcadero released some more software into their [museum](http://edn.embarcadero.com/museum/)!  Thanks.

**Comment by the-grue** [comment]
Sorry I am late for the party!  I just discovered this the other day.  

It is perfectly legal (though not very helpful) to install everything in the Borland toolchain into c:\borlandc.  I used to see this all the time in the labs back in college in the mid 90s.  I believe several of the items identified as issues for this repo would go away if #8 were addressed.  Then someone could update the build script to work with the new environment.

That said, few of us have the required tools, talent, and/or patience to resurrect this OS under the original toolchain.  I believe putting some time into #13 might be worthwhile.

I wouldn't mind helping with these things.  This seems like it will be a lot of fun.  Also, since I never seem to be able to part with old software and books, I have a library of useful information at home.

Default:

![screenshot from 2018-04-25 13-31-21](https://user-images.githubusercontent.com/3101080/39272116-d9a2d924-488f-11e8-8e99-ddab7e086584.png)

Modified:

![screenshot from 2018-04-25 13-33-31](https://user-images.githubusercontent.com/3101080/39272121-df3317f0-488f-11e8-82a6-ea5cd2c24c98.png)

Result:

![screenshot from 2018-04-25 13-51-23](https://user-images.githubusercontent.com/3101080/39272128-e369580c-488f-11e8-87d5-3fd4d415faf4.png)

**Comment by dcoshea** [comment]
@the-grue Oh yeah, I forgot about that.  It might be nicer if the build worked with a *default* install of Borland C++.  On the other hand, you don't want your executables in really deep directory structures because there is only so much environment space available by default, although I don't think `c:\borlandc\bin` is so long as to be a problem.

Anyway, it seems likely then that the original developers installed Borland C++ this way, and documenting that it should be installed in that way seems to me to be a reasonable way of addressing this bug instead of modifying `MAKEMOS.BAT`.

**Comment by andrewbird** [comment]
The current `MAKEMOS.BAT` only appends to the existing users PATH and doesn't specify Borland's path at all. You can set any location for the Borland toolchain  in the current path before running the batch file and that will be respected. I think this issue can now be closed?

**Comment by roelandjansen** [comment]
fair enough.
