### ISSUE TITLE
What next

### ISSUE THREAD

**Issue by src153** [roelandjansen/pcmos386v501#64]
Roeland added collaborators to edit the wiki. I'm not sure he expected us to have write access to the whole repo. But that seems to be true, I was able to merge the patched 9 user floppy image from @the-grue.

With the date bug fixed, there are strong differences of opinion on how to proceed. I think radical changes should be done in a separate branch. A conservative approach could have its own branch too. But I lack the git skills to set those up.

We need to hear from Roeland. Is he OK with us making big changes to his project? I only see two collaborators so far. Are there more?

**Comment by src153** [comment]
And before anyone jumps the gun and starts creating branches without discussing it: most of the project can be shared among all branches. It's the source tree where disputes begin. My idea:

All branches must agree before patching master, it would be the common area everyone agrees on. Fixing that up will take some work, there are only a few patches I want in a conservative branch. The date bug fix, reworked into a single patch instead of two, also the /ref cleanup by @the-grue, I don't think that changes any source files, and a few other patches.

Once master is reduced to a common set of agreed patches, each branch would cherry pick all other previous patches to get their branch where they want it. That sounds like a lot of work, and it probably is. But I've learned a lot in a short time by interacting with people here, and I believe we can be stronger together, while pursuing our own individual goals.

**Comment by the-grue** [comment]
Ultimately, this is Roeland's project and we are sharing and contributing to his repo.  Since we can fork and do what we want with the code, let's leave commits up to him and re-imagine anything he doesn't want to include in branches within our own forks.

**Comment by src153** [comment]
I don't think Roeland has time to be very active in the project. Maybe he wants to delegate management to others he trusts. He can speak for himself on that. That's why I asked for his word, as above.

For the most part, new visitors will not look into forks to find interesting work. I want to see more participants. Maybe some people like a certain branch and want to work on that. Or maybe others want to have their own branch. There's no fear of uncontrolled growth. It will take at least a collaborator to establish a new branch. Random people can't just do it on their own.

**Comment by src153** [comment]
This still open? If no one else closes it, later I will.

There's a problem with 4a07a0a1c462f727ed9d04c546a2df2065fffe3d. If you want to know what, ask and I'll tell. If not, enjoy the error.

I made a fork so now I'm learning git. It's not too bad, with Git for Windows and its bash command line. Google is like Git for dummies. I don't know much, but I just google and there's the answer. I even figured out how to create a branch, which is why I'm posting here.

If you want to use my repo with your own branch, come on over. Why? Because I will make you a collaborator and you won't have to wait for a sometimes absent owner to merge. You can send changes back to this repo from your branch, the best of both worlds. All this assumes I can find the github checkbox to make you a collaborator. Only rule is, don't mess with my branch and I won't mess with yours.

I'm getting things organized now. May take a while. In my repo:

a) "master" mirrors this repo to keep up with its changes
b) "common" is a cherry picked subset which other branches are based on
c) "conservative" is my branch
d) your branch is named radical, anarchist, something that describes you

**Comment by src153** [comment]
Yeah I know but issues are not shared

**Comment by src153** [comment]
Wiki not shared either, You have any more discouraging observations?

**Comment by drawkula** [comment]
Then it makes the most sense to keep issues and the wiki here.
Fragmenting information is no solution.

> You have any more discouraging observations?

Be less negative and think about coming back.

**Comment by src153** [comment]
The truth is not negative. The truth is not rude. When it hurts, it's your error.

I won't come back because I don't have time to correct all the mistakes made here. And the owner merges them. He doesn't know. You want professionalism? Professionals don't make errors and keep their job. If this was a real world job project, I would have to fire a lot of people.

Nothing personal, it's just a question of how I spend my time. The skills of some contributors here are not fully developed. But they're young, they can keep working at it. I'm not, and my time is limited.

**Comment by the-grue** [comment]
> I would have to fire a lot of people.

@src153 

See, here is where you went off the rails.  You are not in a position of authority on this project.  You can't take it upon yourself to assume you do have authority and start pushing people around.  Getting the title "collaborator" doesn't mean you are in a position of authority.  You can't fire people, they come and go at their leisure and contribute what they want or can.  All you can do is drive folks away or cheer them on and make them want to be a part of the fun.

My loyalty to this project, such as it is, is to @roelandjansen as the project owner and, in my opinion, the one who should be guiding the project as well as to myself, learning, and having fun.  That's why I didn't let the title "collaborator" go to my head.  It was given so we could contribute to the wiki, not so we could attempt to take over the project and go on some wildly inappropriate power trip.  As I mentioned before, if you want to run your own ship, fork it and go.

Now, I saw in the early stages of your repo you removed the readme, the license, and various other files.  I'm glad you reconsidered this as it is a bit of a dick move and against the spirit of open source to 1, attempt to claim others' work as your own and 2, remove the license that is supposed to stay with the code.

As a leader of people in the real world, I understand that you have to treat people with respect and dignity.  The way you have treated people on this project has been less than becoming a leader, so you wouldn't have to worry about firing anyone.  Nobody would want to work with you.

**Comment by src153** [comment]
The early stages are experimentation to see what's possible and what's not. If "dick moves" bother you, enjoy the error here.

**Comment by the-grue** [comment]
The error leaves when you sign off.

Bye.
